import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import securityPlugin from "eslint-plugin-security";
import noSecretsPlugin from "eslint-plugin-no-secrets";

/**
 * Rules the project already states in prose (CLAUDE.md, REVIEW.md) are worth
 * more once a machine checks them. Each entry below is an existing written
 * rule moved from "agreed" to "enforced".
 */
const lumeRules = {
  files: ["src/**/*.{ts,tsx}"],
  plugins: {
    security: securityPlugin,
    "no-secrets": noSecretsPlugin,
  },
  rules: {
    /**
     * Design system: colour comes from CSS variables, never from a literal.
     * There are currently zero violations, so this is an error — it locks in an
     * invariant that already holds rather than declaring a cleanup debt.
     */
    "no-restricted-syntax": [
      "error",
      {
        selector:
          'JSXAttribute[name.name="className"] Literal[value=/#[0-9a-fA-F]{3,8}\\b/]',
        message:
          "Hardcoded colour in className. Use a design-system variable, e.g. text-[var(--text-primary)].",
      },
      {
        selector:
          'JSXAttribute[name.name="className"] TemplateElement[value.raw=/#[0-9a-fA-F]{3,8}\\b/]',
        message:
          "Hardcoded colour in className. Use a design-system variable, e.g. text-[var(--text-primary)].",
      },
      {
        selector:
          'JSXAttribute[name.name="className"] Literal[value=/\\brgba?\\(/]',
        message:
          "Hardcoded colour in className. Use a design-system variable instead of rgb()/rgba().",
      },
      {
        // `background` is in the list because leaving it out is exactly how a
        // literal slipped past this rule: the shorthand is the natural thing to
        // write, and the rule only knew the longhand.
        selector:
          'JSXAttribute[name.name="style"] Property[key.name=/^(color|background|backgroundColor|backgroundImage|borderColor|border|outlineColor|boxShadow|fill|stroke)$/] > Literal[value=/(^|\\s)(#[0-9a-fA-F]{3,8}\\b|rgba?\\()/]',
        message:
          "Hardcoded colour in a style prop. Use a design-system variable — or name the constant in globals.css if it is deliberately theme-independent.",
      },
    ],

    /**
     * tsconfig sets noUncheckedIndexedAccess; a non-null assertion silently
     * undoes it. This was a warning while 37 call sites predated the rule. All
     * 37 are gone — several were hiding real faults, not style — so the debt is
     * cleared and the rule is now an error. Do not lower it again; narrow the
     * type or guard the value instead.
     */
    "@typescript-eslint/no-non-null-assertion": "error",

    /**
     * Same plugins the server has run all along. The client is where the keys
     * actually live, so having the weaker lint of the two was backwards.
     *
     * Severities match the server's so a rule does not mean two different things
     * in one repository. object-injection and timing-attacks stay warnings
     * because both are noisy on legitimate code; the rest are errors.
     */
    "security/detect-unsafe-regex": "error",
    "security/detect-buffer-noassert": "error",
    "security/detect-eval-with-expression": "error",
    /**
     * Off, deliberately, and not because it was inconvenient. It fires on every
     * `obj[key]` with a non-literal key — 76 hits here, all of them keyed
     * lookups into typed `Record`s in the Zustand stores (chat id, message id),
     * none of them the `obj[userInput] = …` prototype-pollution shape the rule
     * exists to catch. Left on as a warning it would sit unread, which is the
     * state this whole pass was cleaning up; left on as an error it would invite
     * a blanket disable.
     *
     * Re-enabling it means auditing those 76 sites one by one. That is a focused
     * pass, tracked separately, not a drive-by.
     */
    "security/detect-object-injection": "off",
    "security/detect-non-literal-regexp": "warn",
    "security/detect-possible-timing-attacks": "warn",

    /**
     * A high-entropy string literal in the client is either a mistake or a key.
     * Tolerance matches the server's.
     */
    "no-secrets/no-secrets": ["error", { tolerance: 4.5 }],
  },
};

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  lumeRules,
  {
    // In tests, a missing value is itself the failure, so the assertion is fine.
    files: ["src/__tests__/**/*.{ts,tsx}"],
    rules: { "@typescript-eslint/no-non-null-assertion": "off" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage`; not source, and its vendored
    // report scripts carry their own eslint directives.
    "coverage/**",
  ]),
]);

export default eslintConfig;
